📦
777 /index.js.map
558 /index.js
1692 /agent/Utils.js.map
937 /agent/Utils.js
✄
{"version":3,"file":"index.js","names":["HookApp","hook","getPointer","getClassMethod","appBaseAddr","ths","retv","replace","ptr","args","Interceptor","NativeFunction","target","NativeCallback","console","log"],"sourceRoot":"/Users/panghoo/Code/crack/ishot/frida-agent-macos/","sources":["index.ts"],"mappings":"kBAASA,MAAoB,mBAE7BA,EAAQ,mBAAmB,CAACC,EAAMC,EAAYC,EAAgBC,KAC5DH,EACEE,EAAe,YAAa,8CAC5B,CAACE,EAAKC,KACJA,EAAKC,QAAQC,IAAI,GAAG,IAEtB,CAACH,EAAKI,KAAN,IAIFR,EACEE,EAAe,YAAa,yCAC5B,CAACE,EAAKC,KACJA,EAAKC,QAAQC,IAAI,GAAG,IAEtB,CAACH,EAAKI,KAAN,IAGFR,EACEE,EAAe,YAAa,sCAC5B,CAACE,EAAKC,KACJA,EAAKC,QAAQC,IAAI,GAAG,IAEtB,CAACH,EAAKI,KAAN,IAGFC,YAAYH,QACV,IAAII,eACFR,EAAe,4BAA6B,cAAcS,OAC1D,OACA,IAEF,IAAIC,gBACF,WACEC,QAAQC,IAAI,wBACd,GACA,OACA,IAEH","ignoreList":[]}
✄
import{HookApp as e}from"./agent/Utils.js";e("Navicat Premium",((e,i,r,t)=>{e(r("IAPHelper","- productSubscriptionStillHaveTrialPeriod"),((e,i)=>{i.replace(ptr(0))}),((e,i)=>{})),e(r("IAPHelper","- isProductSubscriptionInGracePeriod"),((e,i)=>{i.replace(ptr(0))}),((e,i)=>{})),e(r("IAPHelper","- isProductSubscriptionStillValid"),((e,i)=>{i.replace(ptr(1))}),((e,i)=>{})),Interceptor.replace(new NativeFunction(r("AppStoreReceiptValidation","+ validate").target,"void",[]),new NativeCallback((function(){console.log("Hook ptrace Bypass!!!")}),"void",[]))}));
✄
{"version":3,"file":"Utils.js","names":["log","message","console","AccessType","HookApp","module","hookStart","appBaseAddr","Module","findBaseAddress","target","leave","enter","line","repeat","Interceptor","attach","onEnter","args","msgTag","this","onLeave","retval","attachTarget","offsetMemmory","add","toString","accessType","Pointer","clazzName","clazzMethodSign","ObjC","classes","implementation","ObjectCFunction","watchMemory","MemoryAccessMonitor","enable","base","NativePointer","size","onAccess","details","from","sub","init"],"sourceRoot":"/Users/panghoo/Code/crack/ishot/frida-agent-macos/agent/","sources":["Utils.ts"],"mappings":"OAAM,SAAUA,OAAOC,GACrBC,QAAQF,OAAOC,EACjB,CAEA,IAAKE,GAAL,SAAKA,GACHA,IAAA,qBACAA,IAAA,oCACD,CAHD,CAAKA,MAAU,YAeT,SAAUC,QACdC,EACAC,GAiBA,IAAIC,EAAcC,OAAOC,gBAAgBJ,GACzCL,IAAI,QAAQK,YAAiBE,KAgDV,MAAfA,GA/CO,CAACA,IAQVD,GAPW,CACTI,EACAC,EACAC,MA8CN,SACEF,EACAH,EACAK,EACAD,EACAN,GAEA,IAAIQ,EAAO,IAAIC,OAAO,IACtBC,YAAYC,OAAON,EAAOA,OAAQ,CAChCO,QAAiCC,GAC/BlB,IAAIa,EAAO,MAAMR,UAAiBK,EAAOS,OAAS,MAClDP,IAAQQ,KAAMF,GACdlB,IAAIa,EAAM,KACZ,EACAQ,QAAQC,GACNtB,IAAIa,EAAO,MAAMR,UAAiBK,EAAOS,OAAS,MAClDnB,IAAI,SAAUsB,GACdX,IAAQS,KAAME,GACdtB,IAAI,SAAUsB,EAAQ,KAAOT,EAAM,KACrC,GAEJ,CAjEMU,CAAab,EAAQH,EAAaK,EAAOD,EAAON,EAAO,IAKrDmB,IAEO,CACLd,OAAQH,EAAYkB,IAAID,GACxBL,OAAQ,KAAOK,EAAcE,SAAS,IACtCC,WAAYxB,EAAWyB,YAG3B,CAACC,EAAmBC,KACX,CACLpB,OAAQqB,KAAKC,QAAQH,GAAWC,GAAiBG,eACjDN,WAAYxB,EAAW+B,gBACvBf,OAAQU,EAAY,KAAOC,EAAkB,OAGjDvB,EACA,CACE4B,YAAczB,IACZ0B,oBAAoBC,OAClB,CACEC,KAAM,IAAIC,cAAc7B,EAAOA,QAC/B8B,KAAM,IAER,CACEC,SAAU,SAAUC,GAClB1C,IACE,OAASU,EAAOS,OAAS,QACzBuB,EAAQC,KAAKC,IAAIrC,GAAamB,WAElC,GAEH,GAGN,EAEsBmB,CAAKtC,EAChC","ignoreList":[]}
✄
export function log(...n){console.log(...n)}var n;!function(n){n[n.Pointer=0]="Pointer",n[n.ObjectCFunction=1]="ObjectCFunction"}(n||(n={}));export function HookApp(t,e){var o=Module.findBaseAddress(t);log(`App [${t}] 内存基址: ${o}`);null!=o&&(o=>{e(((n,e,o)=>{!function(n,t,e,o,a){var g="=".repeat(32);Interceptor.attach(n.target,{onEnter(t){log(g+` \n${a} 进入函数 `+n.msgTag+"\n"),e?.(this,t),log(g,"\n")},onLeave(t){log(g+` \n${a} 退出函数 `+n.msgTag+"\n"),log("修改前返回值",t),o?.(this,t),log("修改后返回值",t,"\n"+g,"\n")}})}(n,0,o,e,t)}),(t=>({target:o.add(t),msgTag:"0x"+t.toString(16),accessType:n.Pointer})),((t,e)=>({target:ObjC.classes[t][e].implementation,accessType:n.ObjectCFunction,msgTag:t+" ["+e+"]"})),o,{watchMemory:n=>{MemoryAccessMonitor.enable({base:new NativePointer(n.target),size:16},{onAccess:function(t){log("对内存["+n.msgTag+"]访问来自",t.from.sub(o).toString())}})}})})(o)}