📦
1175 /index.js.map
756 /index.js
1686 /agent/Utils.js.map
937 /agent/Utils.js
✄
{"version":3,"file":"index.js","names":["HookApp","hook","getPointer","getClassMethod","appBaseAddr","ths","retv","console","log","data","ObjC","Object","key_receipt","classes","NSString","stringWithString_","receipt","objectForKeyedSubscript_","key_in_app","key_expires_date_ms","dict","NSMutableDictionary","alloc","init","setObject_forKey_","info_array","NSMutableArray","addObject_","receipt1","mutableCopy","replace_data","replace","args"],"sourceRoot":"/Users/panghoo/Code/crack/frida-agent-macos/","sources":["index.ts"],"mappings":"kBAASA,MAAoB,mBAE7BA,EAAQ,WAAW,CAACC,EAAMC,EAAYC,EAAgBC,KACpDH,EACEE,EACE,sBACA,wCAEF,CAACE,EAAKC,KAEJC,QAAQC,IAAI,4BACZ,IAAIC,EAAO,IAAIC,KAAKC,OAAOL,GACvBM,EAAcF,KAAKG,QAAQC,SAASC,kBAAkB,WACtDC,EAAUP,EAAKQ,yBAAyBL,GACxCM,EAAaR,KAAKG,QAAQC,SAASC,kBAAkB,UACrDI,EACFT,KAAKG,QAAQC,SAASC,kBAAkB,mBAEtCK,EAAOV,KAAKG,QAAQQ,oBAAoBC,QAAQC,OACpDH,EAAKI,kBAAkB,cAAeL,GAEtC,IAAIM,EAAaf,KAAKG,QAAQa,eAAeJ,QAAQC,OACrDE,EAAWE,WAAWP,GACtB,IAAIQ,EAAWZ,EAAQa,cACvBD,EAASJ,kBAAkBC,EAAYP,GACvC,IAAIY,EAAerB,EAAKoB,cACxBC,EAAaN,kBAAkBI,EAAUhB,GACzCN,EAAKyB,QAAQD,GACbvB,QAAQC,IAAI,qBAAqB,IAEnC,CAACH,EAAK2B,KACJzB,QAAQC,IAAI,4BAA4B,GAE3C","ignoreList":[]}
✄
import{HookApp as t}from"./agent/Utils.js";t("FastZip",((t,e,i,s)=>{t(i("NSJSONSerialization","+ JSONObjectWithData:options:error:"),((t,e)=>{console.log("JSONObjectWithData:  out");let i=new ObjC.Object(e),s=ObjC.classes.NSString.stringWithString_("receipt"),a=i.objectForKeyedSubscript_(s),r=ObjC.classes.NSString.stringWithString_("in_app"),c=ObjC.classes.NSString.stringWithString_("expires_date_ms"),l=ObjC.classes.NSMutableDictionary.alloc().init();l.setObject_forKey_(9999999999999,c);let o=ObjC.classes.NSMutableArray.alloc().init();o.addObject_(l);let n=a.mutableCopy();n.setObject_forKey_(o,r);let b=i.mutableCopy();b.setObject_forKey_(n,s),e.replace(b),console.log("[+] Crack Success!")}),((t,e)=>{console.log("JSONObjectWithDatay: in: ")}))}));
✄
{"version":3,"file":"Utils.js","names":["log","message","console","AccessType","HookApp","module","hookStart","appBaseAddr","Module","findBaseAddress","target","leave","enter","line","repeat","Interceptor","attach","onEnter","args","msgTag","this","onLeave","retval","attachTarget","offsetMemmory","add","toString","accessType","Pointer","clazzName","clazzMethodSign","ObjC","classes","implementation","ObjectCFunction","watchMemory","MemoryAccessMonitor","enable","base","NativePointer","size","onAccess","details","from","sub","init"],"sourceRoot":"/Users/panghoo/Code/crack/frida-agent-macos/agent/","sources":["Utils.ts"],"mappings":"OAAM,SAAUA,OAAOC,GACrBC,QAAQF,OAAOC,EACjB,CAEA,IAAKE,GAAL,SAAKA,GACHA,IAAA,qBACAA,IAAA,oCACD,CAHD,CAAKA,MAAU,YAeT,SAAUC,QACdC,EACAC,GAiBA,IAAIC,EAAcC,OAAOC,gBAAgBJ,GACzCL,IAAI,QAAQK,YAAiBE,KAgDV,MAAfA,GA/CO,CAACA,IAQVD,GAPW,CACTI,EACAC,EACAC,MA8CN,SACEF,EACAH,EACAK,EACAD,EACAN,GAEA,IAAIQ,EAAO,IAAIC,OAAO,IACtBC,YAAYC,OAAON,EAAOA,OAAQ,CAChCO,QAAiCC,GAC/BlB,IAAIa,EAAO,MAAMR,UAAiBK,EAAOS,OAAS,MAClDP,IAAQQ,KAAMF,GACdlB,IAAIa,EAAM,KACZ,EACAQ,QAAQC,GACNtB,IAAIa,EAAO,MAAMR,UAAiBK,EAAOS,OAAS,MAClDnB,IAAI,SAAUsB,GACdX,IAAQS,KAAME,GACdtB,IAAI,SAAUsB,EAAQ,KAAOT,EAAM,KACrC,GAEJ,CAjEMU,CAAab,EAAQH,EAAaK,EAAOD,EAAON,EAAO,IAKrDmB,IAEO,CACLd,OAAQH,EAAYkB,IAAID,GACxBL,OAAQ,KAAOK,EAAcE,SAAS,IACtCC,WAAYxB,EAAWyB,YAG3B,CAACC,EAAmBC,KACX,CACLpB,OAAQqB,KAAKC,QAAQH,GAAWC,GAAiBG,eACjDN,WAAYxB,EAAW+B,gBACvBf,OAAQU,EAAY,KAAOC,EAAkB,OAGjDvB,EACA,CACE4B,YAAczB,IACZ0B,oBAAoBC,OAClB,CACEC,KAAM,IAAIC,cAAc7B,EAAOA,QAC/B8B,KAAM,IAER,CACEC,SAAU,SAAUC,GAClB1C,IACE,OAASU,EAAOS,OAAS,QACzBuB,EAAQC,KAAKC,IAAIrC,GAAamB,WAElC,GAEH,GAGN,EAEsBmB,CAAKtC,EAChC","ignoreList":[]}
✄
export function log(...n){console.log(...n)}var n;!function(n){n[n.Pointer=0]="Pointer",n[n.ObjectCFunction=1]="ObjectCFunction"}(n||(n={}));export function HookApp(t,e){var o=Module.findBaseAddress(t);log(`App [${t}] 内存基址: ${o}`);null!=o&&(o=>{e(((n,e,o)=>{!function(n,t,e,o,a){var g="=".repeat(32);Interceptor.attach(n.target,{onEnter(t){log(g+` \n${a} 进入函数 `+n.msgTag+"\n"),e?.(this,t),log(g,"\n")},onLeave(t){log(g+` \n${a} 退出函数 `+n.msgTag+"\n"),log("修改前返回值",t),o?.(this,t),log("修改后返回值",t,"\n"+g,"\n")}})}(n,0,o,e,t)}),(t=>({target:o.add(t),msgTag:"0x"+t.toString(16),accessType:n.Pointer})),((t,e)=>({target:ObjC.classes[t][e].implementation,accessType:n.ObjectCFunction,msgTag:t+" ["+e+"]"})),o,{watchMemory:n=>{MemoryAccessMonitor.enable({base:new NativePointer(n.target),size:16},{onAccess:function(t){log("对内存["+n.msgTag+"]访问来自",t.from.sub(o).toString())}})}})})(o)}